### ISSUE TITLE
运行run.sh报错

### ISSUE THREAD

**Issue by Scagin** [SongRb/DeepDiveChineseApps#1]
当我配置好环境，下载完斯坦福的两个工具包，重新运行stb/stb  stage编译完项目之后，开始执行./run.sh -p 8080命令，但是程序报错了。看起来不像是因为我的环境问题，似乎更像是源码的错误。但是我并不擅长于scala语言，能否给我一点修改的意见，应该怎样做才能正常运行程序呢？非常感谢。

Parsing with max_len=1000
17:21:25.733 [main] INFO  e.s.nlp.pipeline.StanfordCoreNLP - Registering annotator segment with class edu.stanford.nlp.pipeline.ChineseSegmenterAnnotator
17:21:25.761 [main] INFO  e.s.nlp.pipeline.StanfordCoreNLP - Adding annotator segment
17:21:37.766 [main] INFO  e.s.n.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/segmenter/chinese/ctb.gz ... done [11.9 sec].
17:21:37.768 [main] INFO  e.s.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit

Exception in thread "main" java.lang.IllegalArgumentException: annotator "ssplit" requires annotation "IsNewlineAnnotation". The usual requirements for this annotator are: tokenize
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:504)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:201)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:194)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:181)
	at com.clearcut.nlp.DocumentParser.<init>(DocumentParser.scala:15)
	at com.clearcut.nlp.Main$delayedInit$body.apply(Main.scala:79)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at com.clearcut.nlp.Main$.main(Main.scala:10)
	at com.clearcut.nlp.Main.main(Main.scala)

**Comment by SongRb** [comment]
Please try `./run.sh -p 8080 -a tokenize`.

**Comment by Scagin** [comment]
Thank you very much, the problem has been solved. But when I run nlp_markup.sh in my deepdive project, there comes another exception, and not any log info show. 

Here is the code to call the parser.
` tsv2json "$@" | "$BAZAAR_HOME"/parser/run.sh -i json -k doc_id -v content -a tokenize `


And here is the log.
```
‘run/RUNNING’ -> ‘20180626/110813.062010586’
‘run/LATEST’ -> ‘20180626/110813.062010586’
2018-06-26 11:08:15.284109 # on localhost.localdomain: deepdive do sentences
2018-06-26 11:08:15.284225 # run/20180626/110813.062010586/plan.sh
2018-06-26 11:08:15.284245 # execution plan for data/sentences
2018-06-26 11:08:15.284257 
2018-06-26 11:08:15.284267 : ## process/init/app ##########################################################
2018-06-26 11:08:15.284278 : # Done: 2018-06-25T15:09:17+0800 (19h 58m 56s ago)
2018-06-26 11:08:15.284288 : process/init/app/run.sh
2018-06-26 11:08:15.284299 : mark_done process/init/app
2018-06-26 11:08:15.284309 : ##############################################################################
2018-06-26 11:08:15.284319 
2018-06-26 11:08:15.284329 
2018-06-26 11:08:15.284339 : ## process/init/relation/articles ############################################
2018-06-26 11:08:15.284350 : # Done: 2018-06-26T10:48:35+0800 (19m 38s ago)
2018-06-26 11:08:15.284360 : process/init/relation/articles/run.sh
2018-06-26 11:08:15.284370 : mark_done process/init/relation/articles
2018-06-26 11:08:15.284380 : ##############################################################################
2018-06-26 11:08:15.284390 
2018-06-26 11:08:15.284400 
2018-06-26 11:08:15.284410 : ## data/articles #############################################################
2018-06-26 11:08:15.284420 : # Done: 2018-06-26T10:48:35+0800 (19m 38s ago)
2018-06-26 11:08:15.284431 : # no-op
2018-06-26 11:08:15.284441 : mark_done data/articles
2018-06-26 11:08:15.284451 : ##############################################################################
2018-06-26 11:08:15.284461 
2018-06-26 11:08:15.284471 
2018-06-26 11:08:15.284481 ## process/ext_sentences_by_nlp_markup #######################################
2018-06-26 11:08:15.284491 # Done: 2018-06-25T15:23:02+0800 (19h 45m 11s ago)
2018-06-26 11:08:15.284501 process/ext_sentences_by_nlp_markup/run.sh
2018-06-26 11:08:15.284512 ++ dirname process/ext_sentences_by_nlp_markup/run.sh
2018-06-26 11:08:15.284522 + cd process/ext_sentences_by_nlp_markup
2018-06-26 11:08:15.284532 + export DEEPDIVE_CURRENT_PROCESS_NAME=process/ext_sentences_by_nlp_markup
2018-06-26 11:08:15.284542 + DEEPDIVE_CURRENT_PROCESS_NAME=process/ext_sentences_by_nlp_markup
2018-06-26 11:08:15.284552 + export DEEPDIVE_LOAD_FORMAT=tsv
2018-06-26 11:08:15.284659 + DEEPDIVE_LOAD_FORMAT=tsv
2018-06-26 11:08:15.284673 + deepdive compute execute 'input_sql= SELECT R0.id AS "articles.R0.id", R0.description AS "articles.R0.description"
2018-06-26 11:08:15.284684 FROM articles R0
2018-06-26 11:08:15.284694         
2018-06-26 11:08:15.284704           ' 'command="$DEEPDIVE_APP"/udf/nlp_markup.sh' output_relation=sentences
2018-06-26 11:08:15.343667 Executing with the following configuration:
2018-06-26 11:08:15.343761  DEEPDIVE_NUM_PROCESSES=1
2018-06-26 11:08:15.343780  DEEPDIVE_NUM_PARALLEL_UNLOADS=1
2018-06-26 11:08:15.343791  DEEPDIVE_NUM_PARALLEL_LOADS=1
2018-06-26 11:08:15.343802  output_relation_tmp=dd_tmp_sentences
2018-06-26 11:08:15.343812 
2018-06-26 11:08:15.457738 CREATE TABLE
2018-06-26 11:08:15.534474 CREATE TABLE
2018-06-26 11:08:15.608276 unloading to feed_processes-1: ' SELECT R0.id AS "articles.R0.id", R0.description AS "articles.R0.description"
2018-06-26 11:08:15.608352 FROM articles R0
2018-06-26 11:08:15.608372         
2018-06-26 11:08:15.608383           '
2018-06-26 11:08:15.608394 Loading dd_tmp_sentences from output_computed-1 (tsv format)
unloading: 0:00:00  385 B [20.5KiB/s] ([20.5KiB/s])

unloading: 0:00:00    1  [53.5 /s] ([53.5 /s])

2018-06-26 11:08:15.952537 Parsing with max_len=1000
loading dd_tmp_sentences: 0:00:00    3  [3.47 /s] ([3.47 /s])s])
2018-06-26 11:08:16.505226 错误:  字段 "sentence_index" 缺少数据
2018-06-26 11:08:16.505284 背景:  COPY dd_tmp_sentences, 行 1: "11:08:16.202 [main] INFO  e.s.nlp.pipeline.StanfordCoreNLP - Registering annotator segment with clas..."
2018-06-26 11:08:16.509585 /root/local/util/compute-driver/local/compute-execute: line 140: kill: (3869) - 没有那个进程
2018-06-26 11:08:16.509641 /root/local/util/compute-driver/local/compute-execute: line 140: kill: (3873) - 没有那个进程
2018-06-26 11:08:16.509654 /root/local/util/compute-driver/local/compute-execute: line 140: kill: (3874) - 没有那个进程
2018-06-26 11:08:16.509665 /root/local/util/compute-driver/local/compute-execute: line 140: kill: (3880) - 没有那个进程
2018-06-26 11:08:16.509676 /root/local/util/compute-driver/local/compute-execute: line 140: kill: (3881) - 没有那个进程
‘run/ABORTED’ -> ‘20180626/110813.062010586’

```

**Comment by SongRb** [comment]
Sorry for slow response, there is a complete tutorial and out-of-box DeepDive version for Chinese corpus: [http://openkg.cn/tool/cn-deepdive]()

**Comment by Scagin** [comment]
Doesn't matter and I thank you a lot. I have found the cause of the problem. I can only use the old version `stanford-srparser-2014-10-23-models.jar` , when I use the new version of the Chinese language model, it will report a variety of exceptions. We can overwrite the `./src` folder with java for better compatibility. Thank you any more.
